-- eat / eat

CREATE ROLE eat LOGIN
  PASSWORD 'eat'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL '1970-01-01 00:00:00';


ALTER DATABASE eat
  OWNER TO eat;

ALTER TABLE member
  OWNER TO eat;


--ALTER ROLE eat ENCRYPTED PASSWORD 'eat';